title: Richard Sparkes
logo: /Richard_Photo.jpeg
description: 'PhD Candidate in Economics<br>University of St Andrews<br>PhD Research Intern<br>Monetary Analysis, Bank of England<br><br><a href="Sparkes_CV.pdf">CV</a> | <a href="https://www.linkedin.com/in/richard-sparkes-22a3a3bb">LinkedIn</a>'
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
